# Generated by Django 4.0.4 on 2022-04-26 23:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_albums_owner_alter_images_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
